# Generated by Django 3.0.5 on 2020-04-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200425_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='app.Seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
    ]
