# Generated by Django 3.0.5 on 2020-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200425_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('TOILET_PAPER', 'Toilet Paper'), ('BREAD', 'Bread'), ('PAINKILLERS', 'Painkillers')], max_length=100),
        ),
    ]
