# Generated by Django 3.0.5 on 2020-04-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_seller_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreport',
            name='level',
            field=models.CharField(choices=[('OUT_OF_STOCK', 'Out of stock'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20),
        ),
    ]
